services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - .:/signal23
      - ./data:/signal23/data
    env_file:
      - .env
    environment:
      - PYTHONPATH=/signal23
      - PYTHONUNBUFFERED=1  # Add this for better logging
    depends_on:
      - ollama
    deploy:
      resources:
        limits:
          memory: 1G
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama-data:/root/.ollama
    ports:
      - "11434:11434"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  postgres:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-signal23_ai}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    profiles:
      - pgvector
    deploy:
      resources:
        limits:
          memory: 1G
    restart: unless-stopped

volumes:
  ollama-data:
  postgres-data: