# docker-compose.yml
version: '3.8'

services:
  api:
    build: 
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ./app:/app
      - ./data:/app/data  # For FAISS local storage
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    depends_on:
      - ollama
      # Postgres dependency only when using pgvector profile
      - postgres
    deploy:
      resources:
        limits:
          memory: 1G
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama-data:/root/.ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        limits:
          memory: 4G
    restart: unless-stopped

  # PostgreSQL with pgvector
  postgres:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-signal23_ai}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    # Only start with pgvector profile
    profiles:
      - pgvector
    deploy:
      resources:
        limits:
          memory: 1G
    restart: unless-stopped

volumes:
  ollama-data:
  postgres-data: