services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - .:/signal23
      - ./data:/signal23/data
    env_file:
      - .env
    environment:
      - PYTHONPATH=/signal23
    depends_on:
      - ollama
    deploy:
      resources:
        limits:
          memory: 1G
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama-data:/root/.ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        limits:
          memory: 4G
    restart: unless-stopped

volumes:
  ollama-data: